[package]
description = "Ethcore network library"
homepage = "http://parity.io"
license = "GPL-3.0"
name = "ethcore-network"
version = "1.7.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
log = "0.3"
mio = { git = "https://github.com/ethcore/mio" }
bytes = "0.3.0"
rand = "0.3.12"
time = "0.1.34"
tiny-keccak = "1.0"
rust-crypto = "0.2.34"
slab = "0.2"
clippy = { version = "0.0.103", optional = true}
igd = "0.5.0"
libc = "0.2.7"
parking_lot = "0.3"
ansi_term = "0.9"
rustc-serialize = "0.3"
ethcore-io = { path = "../io" }
ethcore-util = { path = ".." }
ethcore-devtools = { path = "../../devtools" }
ethkey = { path = "../../ethkey" }
ethcrypto = { path = "../../ethcrypto" }
rlp = { path = "../rlp" }
path = { path = "../path" }
ethcore-logger = { path ="../../logger" }

[features]
default = []
dev = ["clippy"]
